## Games in Research

- (Re) Introducing Stephen Thompson
- Work to date - a serious game to study key hole surgery. 
- Opportunities to participate:
  - A literature review on game development in research. 
  - Upcoming project - Exergaming: a serious game for dizziness disorder rehabilitation [#1137](https://github.com/UCL-ARC/arc-opportunities-tracker/issues/1137).

## 🏛️ Introducing Stephen

- Senior Research Software Engineer Since October 2023

- Background in augmented reality for keyhole surgery.
- informus, teaching, EMAP, sense etc.
- Interested in how people collaborate with intelligent machines. 

## 🏛️ Introducing Stephen With Scratch

```{=html}
<iframe src="https://scratch.mit.edu/projects/958976130/embed" allowtransparency="true" width="100%" height="100%" frameborder="0" scrolling="no" allowfullscreen></iframe>
```

## Some Human Interest Pictures

A white tailed sea eagle. Something on the water. Cricket. Bicycle.

## Beginning of Games for Research - SciKit-SurgeryFRED

```{=html}
<iframe width="90%" height="80%" src="https://scikit-surgeryfred.ew.r.appspot.com/" title="SciKit-SurgeryFRED"></iframe>
```

## 2023 Blood Vessel Game

```{=html}
<iframe width="100%" height="80%" src="https://scikit-surgery.github.io/Blood-Vessel-Game/" title="The first blood vessel game."></iframe>
```

<https://github.com/SciKit-Surgery/Blood-Vessel-Game>

## Publication - JMIR Serious Games

```{=html}
<iframe width="100%" height="80%" src="https://games.jmir.org/2025/1/e56269/" title="Webpage example"></iframe>
```

Task performance time is linked to field of view.
## With Self Citation

```{=html}
<iframe width="100%" height="60%" src="https://github.com/phaserjs/phaser/commit/32c82ef7283feb85eff71ab4f5298ff17fd8e3c4" title="Webpage example"></iframe>
```

<https://github.com/phaserjs/phaser/commit/32c82ef7283feb85eff71ab4f5298ff17fd8e3c4>

## 2024 Vessel Game

```{=html}
<iframe width="100%" height="60%" src="https://vessel-game.ew.r.appspot.com/" title="The second blood vessel game"></iframe>
```

<https://github.com/SciKit-Surgery/vessel-game>

## 2025 Blood Vessel Game with Distraction

```{=html}
<iframe width="100%" height="60%" src="https://vessel-game-project.vercel.app/" title="The third blood vessel game."></iframe>
```

<https://github.com/Ash2002-a/Vessel-Game-Project>

## 2025 ARC Blog
```{=html}
<iframe width="100%" src="https://blogs.ucl.ac.uk/research-software-development/using-serious-games-for-research-in-keyhole-surgery/" title="Blog on games for research in keyhole surgery."></iframe>
```

## Game Engines in Research

```{=html}
<iframe width="90%" height="90%" src="https://thompson318.github.io/game_engine_software/" title="A table of game engine software."></iframe>
```

## 🧑💻 Professional expertise

:::columns

:::{.column width="33%"}

::: {.callout-note .nonincremental .fragment icon=false }
## Software engineering
- Create efficient, reliable, reusable & sustainable code​
- Mentor in good practices
:::

:::

:::{.column width="33%"}

::: {.callout-note .nonincremental .fragment icon=false }
## Data science
- Derive insights from data​
- Develop novel algorithms / tools​
- Modelling & simulation
:::

:::

:::{.column width="33%"}

::: {.callout-note .nonincremental .fragment icon=false }
## Data stewardship
- Extracting long-term value from data
- Data engineering & pipelines​
- Publishing (FAIR) data
:::

:::

:::

:::columns

:::{.column width="50%"}

::: {.callout-note .nonincremental .fragment icon=false }
## Infrastructure development
- Design, build & maintain custom hardware & software infrastructure
- Create performant, resilient systems​
:::

:::

:::{.column width="50%"}

::: {.callout-note .nonincremental .fragment icon=false }
## Investment & strategy management
- Supporting & directing research activities​
- Delivery of large-scale projects
:::

:::

:::

::: {.r-fit-text .fragment}
More details at <https://www.ucl.ac.uk/arc/research-technology-professionals​>
::: 

## 🧑‍🏫 Training and support

:::columns

::: {.column width="25%"}

::: {.callout-tip .nonincremental .fragment icon=false }
## MSc modules
- RSE with Python
- Research computing
- Machine learning with big data
- Engineering for data analysis
:::

:::

::: {.column width="25%"}

::: {.callout-tip .nonincremental .fragment icon=false }
## Training
- Becoming a digital researcher
- Improving research software
- Using high performance computing
:::

:::

::: {.column width="25%"}

::: {.callout-tip .nonincremental .fragment icon=false }
## Drop-in & support
- In person and online drop-in sessions
- Slack workspace for community discussion
- Extensive online guides
:::

:::

::: {.column width="25%"}

::: {.callout-tip .nonincremental .fragment icon=false }
## Centre for Doctoral Training
- Collaborative Computational Modelling at the Interface
- Joint venture between UCL & Imperial
- EPSRC funded
:::

:::

:::

::: {.r-fit-text .fragment}
More details at <https://www.ucl.ac.uk/arc/education​>  
:::

## 🖥️ Platforms and services

:::columns

::: {.column .fragment width="50%"}

__Research computing__

::: {.callout-note appearance="minimal"}
Myriad (high throughput computing)
:::

::: {.callout-note appearance="minimal"}
Kathleen (high performance computing)
:::

::: {.callout-note appearance="minimal"}
Contender (novel architectures)
:::

::: {.callout-note appearance="minimal"}
Aristotle, JupyterHub, RStudio (teaching)
:::

::: {.callout-note appearance="minimal"}
Trusted research environment
:::

:::

::: {.column .fragment width="50%"}

__Research data__

::: {.callout-note appearance="minimal"}
Research data storage (ongoing)
:::

::: {.callout-note appearance="minimal"}
Research data repository (archival)
:::

::: {.callout-note appearance="minimal"}
Research data transfer (inter-institution)
:::

::: {.callout-note appearance="minimal"}
Electronic research notebook
:::

::: {.callout-note appearance="minimal"}
Harbour (external data)
:::

:::

:::

::: {.r-fit-text .fragment}
More details at <https://www.ucl.ac.uk/arc/platforms-and-services>  
:::
